default: &default
  adapter: postgresql
  encoding: unicode
  username:
  pool: 5

development:
  <<: *default
  database: oodls_development


test:
  <<: *default
  database: oodls_test


production:
  <<: *default
  database: oodls_production
  username: oodls
  password: <%= ENV['OODLS_DATABASE_PASSWORD'] %>
